<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"校级人员管理",
			            "menuJump":"列表",
			            "tableName":"xiaoji"
			        }
			    ],
			    "menu":"校级人员管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"院级人员管理",
			            "menuJump":"列表",
			            "tableName":"yuanji"
			        }
			    ],
			    "menu":"院级人员管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"实验室人员管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"实验室人员管理"
			}
			,{
			    "child":[
			       {
			           "buttons":[
			               "查看",
			               "新增",
			               "修改",
			               "删除"
			           ],
			           "menu":"实验室管理",
			           "menuJump":"列表",
			           "tableName":"dictionaryShiyanshi"
			       }
			    ],
			    "menu":"实验室管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"实验室设备管理",
                        "menuJump":"列表",
                        "tableName":"shebei"
                    }
                ],
                "menu":"实验室设备管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"设备类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryShebei"
			        }
			        ,
			    ],
			    "menu":"设备类型管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"公告信息管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告信息管理"
			}
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改"
			            ],
			            "menu":"院级人员管理",
			            "menuJump":"列表",
			            "tableName":"yuanji"
			        }
			    ],
			    "menu":"院级人员管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改"
			            ],
			            "menu":"实验室人员管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"实验室人员管理"
			}
			,{
			    "child":[
			       {
			           "buttons":[
			               "查看",
			               "新增",
			               "修改"
			           ],
			           "menu":"实验室管理",
			           "menuJump":"列表",
			           "tableName":"dictionaryShiyanshi"
			       }
			    ],
			    "menu":"实验室管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "审核"
	                    ],
	                    "menu":"实验室设备管理",
	                    "menuJump":"列表",
	                    "tableName":"shebei"
	                }
	            ],
	            "menu":"实验室设备管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改"
			            ],
			            "menu":"设备类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryShebei"
			        }
			        ,
			    ],
			    "menu":"设备类型管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告信息管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告信息管理"
			}
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"校级人员",
	    "tableName":"xiaoji"
	}
	,
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改"
			            ],
			            "menu":"实验室人员管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"实验室人员管理"
			}
			,{
			    "child":[
			       {
			           "buttons":[
			               "查看",
			               "新增",
			               "修改"
			           ],
			           "menu":"实验室管理",
			           "menuJump":"列表",
			           "tableName":"dictionaryShiyanshi"
			       }
			    ],
			    "menu":"实验室管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "审核"
	                    ],
	                    "menu":"实验室设备管理",
	                    "menuJump":"列表",
	                    "tableName":"shebei"
	                }
	            ],
	            "menu":"实验室设备管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改"
			            ],
			            "menu":"设备类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryShebei"
			        }
			        ,
			    ],
			    "menu":"设备类型管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告信息管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告信息管理"
			}
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"院级人员",
	    "tableName":"yuanji"
	}
	,
	
	{
	    "backMenu":[
	        {
			    "child":[
			       {
			           "buttons":[
			               "查看"
			           ],
			           "menu":"实验室管理",
			           "menuJump":"列表",
			           "tableName":"dictionaryShiyanshi"
			       }
			    ],
			    "menu":"实验室管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"实验室设备管理",
	                    "menuJump":"列表",
	                    "tableName":"shebei"
	                }
	            ],
	            "menu":"实验室设备管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告信息管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告信息管理"
			}
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"实验室人员",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
